- id: led_strip
  alias: TV Backlight
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_slider.porch_animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: bruh/porch/set
      payload: '{"transition":{{ trigger.to_state.state | int }}}'

- id: weekday_alarm
  alias: Week day alarm automation
  trigger:
  - minutes: /1
    platform: time
    seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.alarmweekday
    state: 'on'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state
      }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.wakeup

- id: weekend_alarm
  alias: Weekend alarm automation
  trigger:
  - minutes: /1
    platform: time
    seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.alarmweekon
    state: 'on'
  - condition: time
    weekday:
    - sat
    - sun
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state
      }}'
  action:
  - service: script.turn_on
    data:
      entity_id: script.wakeup

- id: turn_on_light_automatically
  alias: Turn on light in evenings
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  condition:
    condition: state
    entity_id: device_tracker.hermesmobile
    state: home
  action:
    service: homeassistant.turn_on
    entity_id: light.my_light


- id: media_idle_light_on
  alias: "Media player paused/stopped"
  trigger:
  - entity_id: media_player.kodi
    platform: state
    from: 'playing'
    to: 'paused'
  - entity_id: media_player.kodi
    platform: state
    from: 'playing'
    to: 'idle'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.room_normal


- id: media_playing_light_off
  alias: "Media player playing"
  trigger:
  - entity_id: media_player.kodi
    platform: state
    from: 'paused'
    to: 'playing'
  - entity_id: media_player.kodi
    platform: state
    from: 'idle'
    to: 'playing'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.room_dim



# Homekit scenes

# - id: good_morning
#   alias: Good Morning Automation
#   trigger:
#   - entity_id: input_boolean.good_morning
#     platform: state
#     to: 'on'
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.wakeup
#
# - id: leave_home
#   alias: Leave Home Automation
#   trigger:
#   - entity_id: input_boolean.leave_home
#     platform: state
#     to: 'on'
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.leaving_home
#
# - id: arrive_home
#   alias: Arrive Home Automation
#   trigger:
#   - entity_id: input_boolean.arrive_home
#     platform: state
#     to: 'on'
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.welcome_home
#
# - id: good_night_auto
#   alias: Goodnight world
#   trigger:
#   - entity_id: input_boolean.enable_night_music
#     platform: state
#     to: 'on'
#   action:
#     - service: script.turn_on
#       data:
#         entity_id: script.good_night




# -id: media_idle_light_on
#   alias: "Media player paused/stopped"
#   trigger:
#   - platform: state
#     entity_id: media_player.kodi
#     from: 'playing'
#     to: 'idle'
#   condition:
#   - condition: state
#     entity_id: sun.sun
#     state: 'below_horizon'
#   action:
#     service: scene.turn_on
#     entity_id: scene.room_normal

# - alias: "Media player playing"
#   trigger:
#     - platform: state
#       entity_id: media_player.htpc
#       to: 'playing'
#       from: 'idle'
#   condition:
#     - condition: state
#       entity_id: sun.sun
#       state: 'below_horizon'
#   action:
#       service: scene.turn_on
#       entity_id: scene.livingroom_dim

# - id: turn_on_light_with_alarm
# alias: Turn on light with alarm
# trigger:
#
# action:
#   service: light.turn_on
#   entity_id: light.my_light
#   data:
#     # 900 seconds = 15 minutes
#     transition: 900
# {{states.sensor.alarm_time.state}}
# #
# # {{now() | replace("-", "**") }}
