- id: loopback
  alias: Loop back test
  trigger:
  - minutes: /1
    platform: time
    seconds: 0
  action: []
- id: led_strip
  alias: TV Backlight
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_slider.porch_animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: bruh/porch/set
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
- id: good_night
  alias: Goodnight world
  trigger:
  - entity_id: input_boolean.enable_night_music
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: media_player.kodi
      media_content_id: plugin://plugin.video.youtube/?path=/root/video&action=play_video&videoid=yhx3JIF7bGU
      media_content_type: video
    service: media_player.play_media
  - alias: volume down kodi
    data:
      entity_id: media_player.kodi
      volume_level: '0.3'
    service: media_player.volume_set
  - alias: night light
    data:
      entity_id: light.my_light
      transition: 5
    service: light.turn_off
- id: weekday_alarm
  alias: Week day alarm automation
  trigger:
  - minutes: /1
    platform: time
    seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.alarmweekon
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarmweekday
    state: 'on'
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state
      }}'
  action:
  - data:
      message: Good morning!
    service: notify.notify
  - alias: Volume UP kodi
    data:
      entity_id: media_player.kodi
      volume_level: '1.0'
    service: media_player.volume_set
  - alias: PLAY lrt
    data:
      entity_id: media_player.kodi
      item:
        channelid: 2
      method: Player.Open
    service: media_player.kodi_call_method
- id: weekend_alarm
  alias: Weekend alarm automation
  trigger:
  - minutes: /1
    platform: time
    seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.alarmweekon
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarmweekday
    state: 'off'
  - condition: time
    weekday:
    - sat
    - sun
  - condition: template
    value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state
      }}'
  action:
  - data:
      message: Good morning!
    service: notify.notify
  - alias: Play rain
    data:
      entity_id: media_player.kodi
      media_content_id: plugin://plugin.video.youtube/?path=/root/video&action=play_video&videoid=x1Nx-tmuHNY
      media_content_type: video
    service: media_player.play_media
  - alias: Volume up kodi
    data:
      entity_id: media_player.kodi
      volume_level: '1.0'
    service: media_player.volume_set
