- id: loopback
  alias: Loop back test
  trigger:
    platform: time
    minutes: /1
    seconds: 0
  action:
  - service: notify.notify
    data:
      message: Beautiful sunset!
- id: led_strip
  alias: TV Backlight
  initial_state: true
  hide_entity: false
  trigger:
  - platform: state
    entity_id: input_slider.porch_animation_speed
  action:
  - service: mqtt.publish
    data_template:
      topic: bruh/porch/set
      payload: '{"transition":{{ trigger.to_state.state | int }}}'
- id: good_night
  alias: Goodnight world
  trigger:
  - entity_id: input_boolean.enable_night_music
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: media_player.kodi
      media_content_id: plugin://plugin.video.youtube/?path=/root/video&action=play_video&videoid=yhx3JIF7bGU
      media_content_type: video
    service: media_player.play_media
