homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Vilnius
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
automation: !include automations.yaml
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret hass_api_password
  base_url: !secret hass_url

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

ios:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml

# tts:
#   platform: google

scene: !include scenes.yaml

script: !include scripts.yaml

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: kodi
    host: omc.local
    port: 8080
    turn_off_action: reboot
    # enable_websocket: false
    # proxy_ssl: false
    username: !secret kodi_username
    password: !secret kodi_password
mqtt:
  broker: 127.0.0.1
  username: !secret mqtt_username
  password: !secret mqtt_password

light:
  - platform: mqtt_json
    name: "Porch Strip"
    state_topic: "bruh/porch"
    command_topic: "bruh/porch/set"
    effect: true
    effect_list:
      - bpm
      - candy cane
      - confetti
      - cyclon rainbow
      - dots
      - fire
      - glitter
      - juggle
      - lightning
      - noise
      - police all
      - police one
      - rainbow
      - rainbow with glitter
      - ripple
      - sinelon
      - solid
      - twinkle
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

  - platform: mqtt_json
    name: "My Light"
    state_topic: "AiLight-B31864"
    command_topic: "AiLight-B31864/set"
    effect: false
    brightness: true
    color_temp: true
    flash: true
    rgb: true
    white_value: true
    xy: true
    optimistic: false
    qos: 0

input_slider:
  porch_animation_speed:
    name: Porch Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  alarmhour:
    name: Hour
    icon: mdi:timer
    initial: 7
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 30
    min: 0
    max: 59
    step: 5

android_ip_webcam:
  - host: 192.168.0.107
    name: hermes_cam
    port: 8080
    scan_interval: 3
    sensors:
      - light
      - battery_temp
      - battery_voltage
    switches:
      - video_recording
      - torch
      - night_vision
      - ffc

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    home_interval: 10
    exclude:
     - 192.168.0.107
     - 192.168.0.1
     - 192.168.0.2
zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:account-multiple

zone 1:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 100
  icon: mdi:worker

input_boolean:
  enable_night_music:
    name: Night vibes
    initial: off
    icon: mdi:sleep
  alarmweekday:
    name: Active weekdays
    initial: on
    icon: mdi:calendar
  alarmweekon:
    name: Active weekends
    initial: on

weblink:
  entities:
    - name: Transmission
      url: http://omc.local:9091
    - name: Sonarr
      url: http://omc.local:8989
    - name: Kodi
      url: http://omc.local:8080/

switch: !include switches.yaml

logger:
  default: warning
  logs:
    homeassistant.components.switch.hdmi: debug

rss_feed_template:
  hass:
    requires_api_password: False
    title: "Home {{ as_timestamp(now())|timestamp_custom('%H:%m', True) }}"
    items:
    - title: "Weather"
      description: "Home temp: {% if is_state('sensor.pws_relative_humidity','unknown') %}---{% else %}{{states.sensor.home_precise_temperature.state}} °C{% endif %}"

group: !include groups.yaml
