# Weather Prediction
- platform: yr

- platform: wunderground
  api_key: !secret wu_key
  monitored_conditions:
    - dewpoint_c
    - temp_c
    - relative_humidity
    - pressure_mb

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
- platform: android_ip_webcam
  resources:
    - type: light
    - type: pressure
    - type: battery_temp

- platform: mqtt
  state_topic: "sensor/hermesnode"
  name: "Home Temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temperature | round(1) }}'
  force_update: true
  icon: mdi:temperature-celsius

- platform: mqtt
  state_topic: "sensor/hermesnode"
  name: "Home Humidity"
  unit_of_measurement: "%"
  value_template: '{{ value_json.humidity | round(1) }}'
  force_update: true
  icon: mdi:water-percent

- platform: mqtt
  state_topic: "sensor/hermesnode"
  name: "Home Precise Temperature"
  unit_of_measurement: "°C"
  value_template: '{{ value_json.temp_precise | round(2) }}'
  force_update: true
  icon: mdi:temperature-celsius

- platform: mqtt
  state_topic: "sensor/hermesnode"
  name: "Home Pressure"
  unit_of_measurement: "mbar"
  value_template: '{{ value_json.pressure | round(2) }}'
  force_update: true
  icon: mdi:thermometer-lines

- platform: transmission
  host: !secret transmission_host
  username: !secret transmission_username
  password: !secret transmission_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: sonarr
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: 8989
  monitored_conditions:
    - diskspace
    - wanted
    - queue
    - upcoming
  days: 3

- platform: dnsip
