- platform: transmission
  name: Slowdown Transmission
  host: omc.local
  username: !secret transmission_username
  password: !secret transmission_password

- platform: hdmi

- platform: command_line
  switches:
    home_assistant_system_shutdown:
      command_off: "/usr/bin/sudo /sbin/reboot"
