- platform: transmission
  name: Slowdown Transmission
  host: omc.local
  username: !secret transmission_username
  password: !secret transmission_password

- platform: hdmi

- platform: command_line
  switches:
    home_assistant_system_shutdown:
      command_off: "/usr/bin/sudo /sbin/reboot"

- platform: mqtt
  name: "Strip Cord"
  command_topic: "cmnd/sonoff/power"
  state_topic: "stat/sonoff/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
